[package]
name = "grpc_matrix"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
futures = "0.3"

[build-dependencies]
tonic-prost-build = "0.14"
